package config

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"log"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"gopkg.in/yaml.v3"
)

type Config struct {
	DBHost     string
	DBPort     string
	DBUser     string
	DBPassword string
	DBName     string
	JWTSecret  string
	EncryptKey string
	Port       string
	InstanceID string
	AdminUser  string
	AdminPass  string

	QueueWorkers          int
	QueuePollMS           int
	QueueMaxAttempts      int
	QueueRetryBackoff     []time.Duration
	QueueClaimTTL         time.Duration
	LogRetentionDays      int
	QueueJobRetentionDays int
	AuditRetentionDays    int

	// TrustedProxies 反向代理 CIDR 列表（逗号分隔）。只有来自这些代理的
	// X-Forwarded-For / X-Real-IP 头才被信任（Webhook IP 白名单依赖）。
	// 默认信任环回地址 + Docker 默认网桥网段（172.16.0.0/12，覆盖 172.17~172.31
	// 各默认网桥）：docker-compose 容器由宿主机 Nginx 反代时，应用看到的连接源是
	// 网桥网关（如 172.18.0.1）而非 127.0.0.1，必须放行才能取到真实客户端 IP。
	TrustedProxies []string
	// EncryptKeyFile 密钥文件路径（ENCRYPT_KEY 未设置时读取/生成此文件）。
	EncryptKeyFile string
	// EncryptKeyAutoGenerated 本次启动的加密密钥是否为自动生成（无 ENCRYPT_KEY 且无密钥文件）。
	EncryptKeyAutoGenerated bool
	// SwaggerEnabled 是否暴露 /swagger API 文档。
	SwaggerEnabled bool
}

// fileConfig 对应 config.yml（键为 kebab-case；指针字段区分「未设置」与「0」）。
type fileConfig struct {
	Server struct {
		Port string `yaml:"port"`
	} `yaml:"server"`
	Database struct {
		Host     string `yaml:"host"`
		Port     string `yaml:"port"`
		User     string `yaml:"user"`
		Password string `yaml:"password"`
		Name     string `yaml:"name"`
	} `yaml:"database"`
	JWTSecret      string `yaml:"jwt_secret"`
	EncryptKey     string `yaml:"encrypt_key"`
	EncryptKeyFile string `yaml:"encrypt_key_file"`
	Admin          struct {
		User string `yaml:"user"`
		Pass string `yaml:"pass"`
	} `yaml:"admin"`
	Queue struct {
		Workers          *int   `yaml:"workers"`
		PollMS           *int   `yaml:"poll_ms"`
		MaxAttempts      *int   `yaml:"max_attempts"`
		RetryBackoff     string `yaml:"retry_backoff"`
		ClaimTTL         *int   `yaml:"claim_ttl"`
		JobRetentionDays *int   `yaml:"job_retention_days"`
	} `yaml:"queue"`
	LogRetentionDays   *int   `yaml:"log_retention_days"`
	AuditRetentionDays *int   `yaml:"audit_retention_days"`
	TrustedProxies     string `yaml:"trusted_proxies"`
	SwaggerEnabled     *bool  `yaml:"swagger_enabled"`
}

// WeakSecretWarnings 返回需要告警的弱密钥配置说明（空表示全部健康）。
// 防止以默认/示例密钥裸跑导致 JWT 可伪造、渠道配置可被解密。
func (c *Config) WeakSecretWarnings() []string {
	var w []string
	if c.JWTSecret == "" || c.JWTSecret == "change-me" || c.JWTSecret == "change_me" {
		w = append(w, "JWT_SECRET 为默认/弱值，JWT 可被伪造，请设置强随机密钥（多实例必须一致）")
	}
	if c.EncryptKey == "" || c.EncryptKey == "0123456789abcdef0123456789abcdef" {
		w = append(w, "ENCRYPT_KEY 为示例固定值，渠道配置加密可被破解，请设置随机 32 字节密钥（多实例必须一致）")
	}
	return w
}

// ConfigPathFromArgs 解析配置路径：--config <path> 或 --config=<path> > CONFIG_FILE 环境变量 > 默认 config.yml。
func ConfigPathFromArgs() string {
	for i := 1; i < len(os.Args); i++ {
		if os.Args[i] == "--config" && i+1 < len(os.Args) {
			return os.Args[i+1]
		}
		if strings.HasPrefix(os.Args[i], "--config=") {
			return strings.TrimPrefix(os.Args[i], "--config=")
		}
	}
	return firstNonEmpty(os.Getenv("CONFIG_FILE"), "config.yml")
}

// Load 从 环境变量 > config.yml > 默认 三通道加载配置（config 路径由 ConfigPathFromArgs 决定）。
func Load() *Config {
	return loadFromPath(ConfigPathFromArgs())
}

// LoadFile 从指定路径加载配置（测试 / 显式 --config 用）。
func LoadFile(path string) *Config {
	return loadFromPath(path)
}

// loadFromPath 合并三通道：默认值 < config.yml < 环境变量（env 优先）。
func loadFromPath(path string) *Config {
	loadDotEnv(".env") // 可选 .env；显式环境变量优先，不会被覆盖
	f := &fileConfig{} // 文件不存在/解析失败时保持零值，仅用默认与环境变量
	if data, err := os.ReadFile(path); err == nil {
		if err := yaml.Unmarshal(data, f); err != nil {
			log.Printf("[警告] 解析配置文件 %s 失败: %v，使用默认/环境变量", path, err)
		}
	}
	encryptKeyFile := firstNonEmpty(os.Getenv("ENCRYPT_KEY_FILE"), f.EncryptKeyFile, keyFile)
	encryptKey, encryptKeyAuto := resolveEncryptKeyWith(f.EncryptKey, encryptKeyFile)
	return &Config{
		DBHost:                  firstNonEmpty(os.Getenv("DB_HOST"), f.Database.Host, "127.0.0.1"),
		DBPort:                  firstNonEmpty(os.Getenv("DB_PORT"), f.Database.Port, "3306"),
		DBUser:                  firstNonEmpty(os.Getenv("DB_USER"), f.Database.User, "notice"),
		DBPassword:              firstNonEmpty(os.Getenv("DB_PASSWORD"), f.Database.Password, "notice123"),
		DBName:                  firstNonEmpty(os.Getenv("DB_NAME"), f.Database.Name, "notice_service"),
		JWTSecret:               firstNonEmpty(os.Getenv("JWT_SECRET"), f.JWTSecret, "change-me"),
		EncryptKey:              encryptKey,
		EncryptKeyFile:          encryptKeyFile,
		EncryptKeyAutoGenerated: encryptKeyAuto,
		Port:                    firstNonEmpty(os.Getenv("PORT"), f.Server.Port, "8080"),
		InstanceID:              getEnv("INSTANCE_ID", uuid.NewString()),
		AdminUser:               firstNonEmpty(os.Getenv("ADMIN_USER"), f.Admin.User, "admin"),
		AdminPass:               firstNonEmpty(os.Getenv("ADMIN_PASS"), f.Admin.Pass, "admin123"),

		QueueWorkers:          firstInt("QUEUE_WORKERS", f.Queue.Workers, 4),
		QueuePollMS:           firstInt("QUEUE_POLL_MS", f.Queue.PollMS, 1000),
		QueueMaxAttempts:      firstInt("QUEUE_MAX_ATTEMPTS", f.Queue.MaxAttempts, 3),
		QueueRetryBackoff:     parseDurations(firstNonEmpty(os.Getenv("QUEUE_RETRY_BACKOFF"), f.Queue.RetryBackoff, "5s,30s,60s"), []time.Duration{5 * time.Second, 30 * time.Second, 60 * time.Second}),
		QueueClaimTTL:         time.Duration(firstInt("QUEUE_CLAIM_TTL", f.Queue.ClaimTTL, 120)) * time.Second,
		LogRetentionDays:      firstInt("LOG_RETENTION_DAYS", f.LogRetentionDays, 90),
		QueueJobRetentionDays: firstInt("QUEUE_JOB_RETENTION_DAYS", f.Queue.JobRetentionDays, 30),
		AuditRetentionDays:    firstInt("AUDIT_RETENTION_DAYS", f.AuditRetentionDays, 180),
		TrustedProxies:        parseCSV(firstNonEmpty(os.Getenv("TRUSTED_PROXIES"), f.TrustedProxies, "127.0.0.1,::1,172.16.0.0/12")),
		SwaggerEnabled:        firstBool("SWAGGER_ENABLED", f.SwaggerEnabled, true),
	}
}

// firstNonEmpty 返回第一个非空值（用于 env > file > default 优先级）。
func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}

// firstInt env（可解析数字）> 配置文件 > 默认。
func firstInt(envKey string, fileVal *int, def int) int {
	if v := os.Getenv(envKey); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	if fileVal != nil {
		return *fileVal
	}
	return def
}

// firstBool env（true/1）> 配置文件 > 默认。
func firstBool(envKey string, fileVal *bool, def bool) bool {
	if v := os.Getenv(envKey); v != "" {
		switch strings.ToLower(strings.TrimSpace(v)) {
		case "1", "true", "yes", "on":
			return true
		case "0", "false", "no", "off":
			return false
		}
	}
	if fileVal != nil {
		return *fileVal
	}
	return def
}

// parseCSV 把逗号分隔的字符串解析为去空格的非空切片（用于 CIDR 列表）。
func parseCSV(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ",") {
		if v := strings.TrimSpace(p); v != "" {
			out = append(out, v)
		}
	}
	return out
}

// keyFile 未显式配置 ENCRYPT_KEY 时用于持久化密钥，保证重启后能解密已存的渠道配置。
const keyFile = ".notice-encrypt.key"

// resolveEncryptKey 优先用环境变量；否则读取本地密钥文件，不存在则生成并持久化。
func resolveEncryptKey() string {
	k, _ := resolveEncryptKeyWith("", keyFile)
	return k
}

// resolveEncryptKeyWith 密钥解析：env ENCRYPT_KEY > config.yml encrypt_key > 密钥文件 > 随机生成。
// 返回 (密钥, 是否自动生成)。自动生成仅在「无显式密钥且无可用密钥文件」时发生。
func resolveEncryptKeyWith(fileKey, filePath string) (string, bool) {
	if v := firstNonEmpty(os.Getenv("ENCRYPT_KEY"), fileKey); v != "" {
		return v, false
	}
	if b, err := os.ReadFile(filePath); err == nil && len(b) >= 32 {
		return string(b[:32]), false
	}
	k := randomHex(16)
	_ = os.WriteFile(filePath, []byte(k), 0o600)
	return k, true
}

func (c *Config) DSN() string {
	return c.DBUser + ":" + c.DBPassword + "@tcp(" + c.DBHost + ":" + c.DBPort + ")/" +
		c.DBName + "?parseTime=true&charset=utf8mb4&loc=Local" +
		"&timeout=5s&readTimeout=10s&writeTimeout=10s"
}

func getEnv(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func getEnvInt(key string, def int) int {
	if v := os.Getenv(key); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	return def
}

// parseDurations 解析逗号分隔的 duration 列表；任一解析失败或为空时回退到 def。
func parseDurations(s string, def []time.Duration) []time.Duration {
	if strings.TrimSpace(s) == "" {
		return def
	}
	parts := strings.Split(s, ",")
	out := make([]time.Duration, 0, len(parts))
	for _, p := range parts {
		d, err := time.ParseDuration(strings.TrimSpace(p))
		if err != nil {
			return def
		}
		out = append(out, d)
	}
	if len(out) == 0 {
		return def
	}
	return out
}

// loadDotEnv 读取简单的 KEY=VALUE 配置文件（每行一条，支持 # 注释与引号）。
// 仅当对应环境变量未设置时才写入，保证显式环境变量优先。
func loadDotEnv(path string) {
	f, err := os.Open(path)
	if err != nil {
		return
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		k = strings.TrimSpace(k)
		v = strings.Trim(strings.TrimSpace(v), `"'`)
		if k == "" {
			continue
		}
		if os.Getenv(k) == "" {
			_ = os.Setenv(k, v)
		}
	}
}

func randomHex(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "0123456789abcdef0123456789abcdef"
	}
	return hex.EncodeToString(b)
}
