package main

import (
	"testing"

	"notice-service/internal/config"
	"notice-service/internal/repository"
)

// TestCheckEncryptKeyPresence 验证 R3：自动生成密钥 + 库里已有密文 → 必须报错拒绝启动。
func TestCheckEncryptKeyPresence(t *testing.T) {
	db := testDB(t)
	repo := repository.NewChannelRepo(db)
	if _, err := db.Exec("DELETE FROM channels"); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec("DELETE FROM users WHERE username LIKE 'enc-%'"); err != nil {
		t.Fatal(err)
	}

	okCfg := &config.Config{EncryptKeyAutoGenerated: false, EncryptKeyFile: ".notice-encrypt.key"}
	if err := checkEncryptKeyPresence(okCfg, repo); err != nil {
		t.Fatalf("explicit key should pass: %v", err)
	}
	autoCfg := &config.Config{EncryptKeyAutoGenerated: true, EncryptKeyFile: ".notice-encrypt.key"}
	if err := checkEncryptKeyPresence(autoCfg, repo); err != nil {
		t.Fatalf("no channels should pass even when auto-generated: %v", err)
	}

	// 插入一个用户 + 带密文的渠道
	res, err := db.Exec("INSERT INTO users (username, password_hash, role) VALUES ('enc-u', 'h', 'user')")
	if err != nil {
		t.Fatal(err)
	}
	uid, _ := res.LastInsertId()
	t.Cleanup(func() {
		db.Exec("DELETE FROM channels WHERE user_id=?", uid)
		db.Exec("DELETE FROM users WHERE id=?", uid)
	})
	if _, err := db.Exec(
		"INSERT INTO channels (user_id, type, name, config_json, enabled) VALUES (?, 'email', 'c', 'ciphertext', 1)", uid); err != nil {
		t.Fatal(err)
	}
	if err := checkEncryptKeyPresence(autoCfg, repo); err == nil {
		t.Fatal("ciphertext exists + auto-generated key -> must error")
	}
}
