package main

import (
	"os"
	"path/filepath"
	"testing"

	"notice-service/internal/config"
	"notice-service/internal/repository"
)

// TestCheckEncryptKeyPresence 验证 R3：自动生成密钥 + 库里已有密文 → 必须报错拒绝启动，
// 且本次自动生成的无效密钥文件必须被移除（防止下次启动误认其为有效密钥而绕过校验）。
func TestCheckEncryptKeyPresence(t *testing.T) {
	db := testDB(t)
	repo := repository.NewChannelRepo(db)
	if _, err := db.Exec("DELETE FROM channels"); err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec("DELETE FROM users WHERE username LIKE 'enc-%'"); err != nil {
		t.Fatal(err)
	}

	okCfg := &config.Config{EncryptKeyAutoGenerated: false, EncryptKeyFile: ".notice-encrypt.key"}
	if err := checkEncryptKeyPresence(okCfg, repo); err != nil {
		t.Fatalf("explicit key should pass: %v", err)
	}
	autoCfg := &config.Config{EncryptKeyAutoGenerated: true, EncryptKeyFile: ".notice-encrypt.key"}
	if err := checkEncryptKeyPresence(autoCfg, repo); err != nil {
		t.Fatalf("no channels should pass even when auto-generated: %v", err)
	}

	// 插入一个用户 + 带密文的渠道
	res, err := db.Exec("INSERT INTO users (username, password_hash, role) VALUES ('enc-u', 'h', 'user')")
	if err != nil {
		t.Fatal(err)
	}
	uid, _ := res.LastInsertId()
	t.Cleanup(func() {
		db.Exec("DELETE FROM channels WHERE user_id=?", uid)
		db.Exec("DELETE FROM users WHERE id=?", uid)
	})
	if _, err := db.Exec(
		"INSERT INTO channels (user_id, type, name, config_json, enabled) VALUES (?, 'email', 'c', 'ciphertext', 1)", uid); err != nil {
		t.Fatal(err)
	}

	// 自动生成 + 已有密文：模拟 resolveEncryptKeyWith 刚把新密钥写入 cfg.EncryptKeyFile。
	// 校验失败时必须连同移除该无效密钥文件，否则下次启动会误认其为有效密钥而静默用错密钥。
	keyPath := filepath.Join(t.TempDir(), "auto.key")
	if err := os.WriteFile(keyPath, []byte("0123456789abcdef0123456789abcdef"), 0o600); err != nil {
		t.Fatal(err)
	}
	fatalCfg := &config.Config{EncryptKeyAutoGenerated: true, EncryptKeyFile: keyPath}
	if err := checkEncryptKeyPresence(fatalCfg, repo); err == nil {
		t.Fatal("ciphertext exists + auto-generated key -> must error")
	}
	if _, err := os.Stat(keyPath); !os.IsNotExist(err) {
		t.Fatalf("auto-generated key file should be removed on fatal path, stat err=%v", err)
	}
}
