package main

// @title Notice Service API
// @version 1.0.0
// @description 自托管通知发送服务 API（邮箱/企微/钉钉/飞书/PushPlus 多渠道投递）。
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization

import (
	"context"
	"crypto/sha256"
	"errors"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"

	"notice-service/internal/config"
	"notice-service/internal/crypto"
	"notice-service/internal/database"
	"notice-service/internal/repository"
	"notice-service/internal/router"
	"notice-service/internal/scheduler"
	"notice-service/internal/service"

	_ "notice-service/docs/swagger" // 注册 Swagger 文档（swag init 生成）
)

// buildVersion 构建版本标识（可用 -ldflags "-X main.buildVersion=..." 覆盖）。
var buildVersion = "dev"

// heartbeatInterval 实例心跳上报间隔（「信号在线」多节点健康）。
const heartbeatInterval = 5 * time.Second

func main() {
	cfg := config.Load()

	// Gin 模式：GIN_MODE 环境变量优先（debug/release/test），默认 release。
	// 必须在创建 engine（router.NewRouter）之前设置，否则启动横幅/请求日志按错误模式输出。
	mode := os.Getenv("GIN_MODE")
	if mode == "" {
		mode = gin.ReleaseMode
	}
	gin.SetMode(mode)

	// reset-password 子命令：唯一 admin 忘记密码时离线重置，不启动 HTTP 服务。
	if len(os.Args) > 1 && os.Args[1] == "reset-password" {
		os.Exit(runResetPasswordCmd(cfg))
	}

	// 弱默认密钥告警：防止以默认/示例密钥裸跑
	for _, w := range cfg.WeakSecretWarnings() {
		log.Printf("[警告] %s", w)
	}

	db, err := database.Open(cfg.DSN())
	if err != nil {
		log.Fatalf("db connect: %v", err)
	}
	defer db.Close()
	if err := database.Migrate(db); err != nil {
		log.Fatalf("migrate: %v", err)
	}

	// R3：自动生成密钥 + 库里已有密文 → 拒绝启动，防静默丢失历史渠道配置。
	if err := checkEncryptKeyPresence(cfg, repository.NewChannelRepo(db)); err != nil {
		log.Fatalf("启动中止: %v", err)
	}

	if cfg.EncryptKeyAutoGenerated {
		// 首启（无任何历史密文）：密钥为自动生成，提示运维立即持久化，防止下次重启密钥变化导致历史渠道配置不可解。
		log.Printf("[警告] 未设置 ENCRYPT_KEY 且未找到密钥文件，已自动生成新密钥并写入 %s。请立即持久化该密钥（设置 ENCRYPT_KEY 环境变量或备份该文件），否则下次重启将无法解密历史渠道配置。", cfg.EncryptKeyFile)
	}

	ciph, err := crypto.New([]byte(padKey(cfg.EncryptKey)))
	if err != nil {
		log.Fatalf("crypto: %v", err)
	}

	authSvc := service.NewAuthService(db, cfg.JWTSecret, cfg.AdminUser, cfg.AdminPass)
	if err := authSvc.BootstrapAdmin(); err != nil {
		log.Fatalf("bootstrap admin: %v", err)
	}

	ns := service.NewNotificationService(db, ciph)

	// 发送队列：入队即落库，worker 池后台消费（重试/崩溃接管/清理都在这层）
	qcfg := service.QueueConfig{
		Workers:            cfg.QueueWorkers,
		PollInterval:       time.Duration(cfg.QueuePollMS) * time.Millisecond,
		MaxAttempts:        cfg.QueueMaxAttempts,
		RetryBackoff:       cfg.QueueRetryBackoff,
		ClaimTTL:           cfg.QueueClaimTTL,
		LogRetentionDays:   cfg.LogRetentionDays,
		JobRetentionDays:   cfg.QueueJobRetentionDays,
		AuditRetentionDays: cfg.AuditRetentionDays,
	}
	queue := service.NewQueueService(db, ns, qcfg, cfg.InstanceID)
	queue.Start()
	defer queue.StopWithTimeout(15 * time.Second)

	// 调度器：cron 到点只做快速入队（毫秒级），带 dedupe key 防极端竞态重复
	sched := scheduler.New(func(taskID int64, dedupeKey string) {
		if _, err := queue.Enqueue(taskID, nil, dedupeKey,
			service.Trigger{Type: "cron", By: "scheduler"}); err != nil {
			log.Printf("scheduler: enqueue task %d failed: %v", taskID, err)
		}
	}, repository.NewTaskRepo(db), cfg.InstanceID)
	sched.Start()
	defer sched.Stop()
	tasks, err := repository.NewTaskRepo(db).ListEnabledCron()
	if err != nil {
		log.Fatalf("load cron tasks: %v", err)
	}
	for _, t := range tasks {
		sched.RegisterTask(t.ID, t.CronExpr)
	}

	// 实例心跳：周期上报自身节点信息，供「信号在线」查看多后端健康；
	// 优雅退出时删除本实例心跳，避免遗留僵尸节点。
	hbRepo := repository.NewHeartbeatRepo(db)
	host, _ := os.Hostname()
	// 启动即清理同主机同端口的历史心跳（仅保留当前实例）。本地反复重启/被强杀
	// 时旧实例行会残留，造成「节点列表显示多个、实际只跑一个」的假象。
	if err := hbRepo.PurgeSameAddr(host, cfg.Port, cfg.InstanceID); err != nil {
		log.Printf("heartbeat: purge stale instances: %v", err)
	}
	startedAt := time.Now()
	hbCtx, hbCancel := context.WithCancel(context.Background())
	var hbWG sync.WaitGroup
	hbWG.Add(1)
	go func() {
		defer hbWG.Done()
		tick := func() {
			_ = hbRepo.Upsert(&repository.Instance{
				InstanceID: cfg.InstanceID, Host: host, Port: cfg.Port, Version: buildVersion,
				StartedAt: startedAt, LastSeenAt: time.Now(),
			})
		}
		tick() // 启动立即上报一次
		ticker := time.NewTicker(heartbeatInterval)
		defer ticker.Stop()
		for {
			select {
			case <-hbCtx.Done():
				_ = hbRepo.Remove(cfg.InstanceID)
				return
			case <-ticker.C:
				tick()
			}
		}
	}()
	defer func() {
		hbCancel()
		hbWG.Wait()
	}()

	engine := router.NewRouter(db, authSvc, ciph, sched, queue, router.Options{
		TrustedProxies: cfg.TrustedProxies,
		SwaggerEnabled: cfg.SwaggerEnabled,
	})
	staticDir, staticOK := resolveStaticDir(cfg.StaticDir)
	if staticOK {
		engine.Static("/assets", filepath.Join(staticDir, "assets"))
		engine.StaticFile("/", filepath.Join(staticDir, "index.html"))
	} else {
		log.Printf("[警告] 未找到静态资源目录（STATIC_DIR=%s，./web/dist，可执行文件同目录均不存在），SPA 页面不可用，API 照常。", cfg.StaticDir)
	}
	engine.NoRoute(func(c *gin.Context) {
		if strings.HasPrefix(c.Request.URL.Path, "/api/") {
			c.JSON(404, gin.H{"error": "not found"})
			return
		}
		if staticOK && c.Request.Method == "GET" {
			c.File(filepath.Join(staticDir, "index.html"))
			return
		}
		c.JSON(404, gin.H{"error": "not found"})
	})

	// 生产级 HTTP 服务器：读/写/空闲超时防慢连接与连接耗尽。
	srv := &http.Server{
		Addr:              ":" + cfg.Port,
		Handler:           engine,
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       10 * time.Second,
		WriteTimeout:      20 * time.Second,
		IdleTimeout:       60 * time.Second,
	}

	// 优雅退出：SIGINT/SIGTERM → 停止接收新连接 → 等待在途请求完成 →
	// 排空发送队列（defer queue.Stop 会在返回后执行）→ 停调度器 → 关 DB。
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	go func() {
		<-ctx.Done()
		log.Printf("收到退出信号，开始优雅关闭（最多 15s）...")
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()
		if err := srv.Shutdown(shutdownCtx); err != nil {
			log.Printf("http shutdown: %v", err)
		}
	}()

	log.Printf("notice-service listening on :%s (instance %s)", cfg.Port, cfg.InstanceID)
	if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatal(err)
	}
}

// runResetPasswordCmd 处理 reset-password 子命令，返回进程退出码。
func runResetPasswordCmd(cfg *config.Config) int {
	username := cfg.AdminUser
	newPassword := ""
	fs := flag.NewFlagSet("reset-password", flag.ContinueOnError)
	fs.StringVar(&username, "username", cfg.AdminUser, "要重置的用户名（默认 ADMIN_USER）")
	fs.StringVar(&newPassword, "new-password", "", "新密码（缺省时交互式输入，不回显）")
	if err := fs.Parse(os.Args[2:]); err != nil {
		return 2
	}
	if newPassword == "" {
		pw, err := promptNewPassword(os.Stdin, os.Stdout)
		if err != nil {
			fmt.Fprintln(os.Stderr, "读取密码失败:", err)
			return 2
		}
		newPassword = pw
	}
	db, err := database.Open(cfg.DSN())
	if err != nil {
		fmt.Fprintln(os.Stderr, "数据库连接失败:", err)
		return 1
	}
	defer db.Close()
	if err := resetPassword(db, username, newPassword); err != nil {
		fmt.Fprintln(os.Stderr, "重置失败:", err)
		return 1
	}
	fmt.Printf("已重置用户 %s 的密码\n", username)
	return 0
}

// checkEncryptKeyPresence 若密钥为自动生成（无 ENCRYPT_KEY 且无密钥文件）而库里已有
// 加密渠道配置，返回错误（应拒绝启动，防静默丢失历史配置）。
func checkEncryptKeyPresence(cfg *config.Config, chRepo *repository.ChannelRepo) error {
	if !cfg.EncryptKeyAutoGenerated {
		return nil
	}
	n, err := chRepo.CountEncrypted()
	if err != nil {
		return err
	}
	if n > 0 {
		return fmt.Errorf("检测到 %d 个已加密渠道配置，但未提供 ENCRYPT_KEY 且密钥文件 %s 不存在，历史渠道配置将无法解密；请设置 ENCRYPT_KEY 或恢复密钥文件", n, cfg.EncryptKeyFile)
	}
	return nil
}

// resolveStaticDir 按优先级解析静态资源目录：配置值 → ./web/dist → 可执行文件同目录 web/dist。
// 返回 (目录, 是否可用)。
func resolveStaticDir(configured string) (string, bool) {
	for _, d := range []string{configured, "./web/dist"} {
		if d != "" && dirExists(d) {
			return d, true
		}
	}
	if exe, err := os.Executable(); err == nil {
		if cand := filepath.Join(filepath.Dir(exe), "web", "dist"); dirExists(cand) {
			return cand, true
		}
	}
	return "", false
}

func dirExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && st.IsDir()
}

// padKey 保证 32 字节：过长截断，过短用 SHA-256 摘要补齐。
func padKey(s string) string {
	if len(s) >= 32 {
		return s[:32]
	}
	sum := sha256.Sum256([]byte(s))
	return string(sum[:])
}
